version: "3"

services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./data/WebData/Course_Document:/app/WebData/Course_Document
      - ./data/WebData/Course_img:/app/WebData/Course_img
      - .:/app
  db:
    depends_on:
      - phpmyadmin
      - web
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - env/db_setting.env
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file:
      - env/pma_setting.env
    ports:
      - '8080:80'